lzc-sdk-version: "0.1"
name: Odoo
package: cloud.lazycat.app.odoo
version: 19.0.0
description: 全球第一开源ERP
homepage: https://www.odoo.com
author: odoo
application:
  subdomain: odoo
  background_task: true
  multi_instance: false

  public_path:
    - /
  routes:
    - /=http://odoo-web:8069/
services:
  odoo-web:
    # odoo:19.0
    image: registry.lazycat.cloud/czyt/library/odoo:a900e2cdc3807576
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=odoo
    depends_on:
      - odoo-db
    binds:
      - /lzcapp/var/data:/var/lib/odoo
      - /lzcapp/var/extra-addons:/mnt/extra-addons
    setup_script: |
      mkdir -p /var/lib/odoo/sessions
      chown -R odoo /var/lib/odoo/sessions

  odoo-db:
    container_name: odoo-db
    image: registry.lazycat.cloud/czyt/library/postgres:4c94230970ec8303
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    binds:
      - /lzcapp/var/db:/var/lib/postgresql/data/pgdata
    health_check:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      start_period: 30s
